package server

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"html/template"
	"log/slog"
	"net/http"
	"os"
	"path/filepath"
	"regexp"

	"github.com/parithosh/piecesoflife/internal/auth"
	"github.com/parithosh/piecesoflife/internal/store"
	"github.com/parithosh/piecesoflife/internal/theme"
)

// Circle appearance: a circle admin picks a fabric, up to three colours and
// optional photos; the operator's instance switch is a ceiling over all of
// it. Enforcement happens where themes are rendered (newPageData and the
// memento page) and on every appearance API — never only in the UI.

// pageTheme is the appearance a page renders with; nil = the house look,
// which emits nothing so pages stay byte-identical to the un-themed app.
type pageTheme struct {
	// CSS is the :root declaration list: palette tokens plus, when photos
	// are shown, --circle-photo/--banner and their focal points.
	CSS       template.CSS
	Main      string
	HasPhoto  bool
	HasBanner bool
}

// LoopEntry is one circle in the nav switcher and on /loops: the
// membership plus its appearance summary (empty when the circle uses the
// house look or appearance is switched off).
type LoopEntry struct {
	store.UserGroup
	Dot      string
	PhotoURL string
	PhotoPos string
}

// brandingFileRe is the only shape a stored circle photo file can take —
// generated by the upload handler, so anything else is a forged reference.
var brandingFileRe = regexp.MustCompile(`^[0-9a-f]{16}\.jpg$`)

const (
	brandingDirName = "branding"
	// maxBrandingUploadBytes bounds a circle photo upload: phone photos are
	// a few MB; 30 MB leaves room for large PNGs.
	maxBrandingUploadBytes = 30 << 20
	circlePhotoEdge        = 640
	bannerEdge             = 2400
)

// appearanceEnabled reports the operator's instance switch.
func (s *Server) appearanceEnabled(ctx context.Context) bool {
	inst, err := s.store.GetInstanceSettings(ctx)
	if err != nil {
		s.logger.ErrorContext(ctx, "Failed to load instance settings",
			slog.String("error", err.Error()))
		return false
	}

	return inst.AllowCircleAppearance
}

// resolveTheme turns a stored config into render data. withPhotos=false for
// surfaces anonymous visitors can reach (public mementos): colours only, so
// no private photo URL ever appears in the page. The caller has already
// checked the instance switch.
func (s *Server) resolveTheme(ctx context.Context, raw json.RawMessage, withPhotos bool) *pageTheme {
	cfg, err := theme.ParseConfig(raw)
	if err != nil {
		s.logger.ErrorContext(ctx, "Ignoring unreadable circle theme",
			slog.String("error", err.Error()))
		return nil
	}
	if cfg == nil {
		return nil
	}

	pal, err := theme.Resolve(cfg)
	if err != nil {
		s.logger.ErrorContext(ctx, "Ignoring invalid circle theme",
			slog.String("error", err.Error()))
		return nil
	}

	pt := &pageTheme{Main: pal.Main}
	decls := pal.Declarations()

	if withPhotos {
		if url := s.brandingURL(cfg.Photo); url != "" {
			pt.HasPhoto = true
			decls += photoDecls("circle-photo", url, cfg.Photo)
		}
		if url := s.brandingURL(cfg.Banner); url != "" {
			pt.HasBanner = true
			decls += photoDecls("banner", url, cfg.Banner)
		}
	}

	// Safe: every value is engine-generated hex/rgb, and photo URLs are
	// built from paths whose file name passed brandingFileRe.
	pt.CSS = template.CSS(decls) //nolint:gosec // see above

	return pt
}

func photoDecls(name, url string, p *theme.Photo) string {
	return fmt.Sprintf(`--%s:url("%s");--%s-pos:%d%% %d%%;`, name, url, name, p.X, p.Y)
}

// brandingURL returns the /uploads URL of a stored circle photo, or "" when
// the reference is absent or doesn't have the shape the uploader produces.
func (s *Server) brandingURL(p *theme.Photo) string {
	if p == nil || !brandingFileRe.MatchString(filepath.Base(p.Path)) {
		return ""
	}

	return s.uploadURL(p.Path)
}

// loopEntries decorates the user's circles with their appearance summary.
func (s *Server) loopEntries(groups []store.UserGroup, enabled bool) []LoopEntry {
	out := make([]LoopEntry, len(groups))
	for i, g := range groups {
		out[i] = LoopEntry{UserGroup: g}
		if !enabled || g.Theme == nil {
			continue
		}

		cfg, err := theme.ParseConfig(g.Theme)
		if err != nil || cfg == nil {
			continue
		}
		if pal, err := theme.Resolve(cfg); err == nil {
			out[i].Dot = pal.Main
		}
		if url := s.brandingURL(cfg.Photo); url != "" {
			out[i].PhotoURL = url
			out[i].PhotoPos = fmt.Sprintf("%d%% %d%%", cfg.Photo.X, cfg.Photo.Y)
		}
	}

	return out
}

// ---- Appearance page ------------------------------------------------------

// appearanceState is the editor's JSON view of a config: photos travel as
// bare file names plus URLs, never as server paths.
type appearanceState struct {
	Fabric    string               `json:"fabric"`
	Main      string               `json:"main"`
	Highlight string               `json:"highlight"`
	Second    string               `json:"second"`
	Photo     *appearancePhotoJSON `json:"photo"`
	Banner    *appearancePhotoJSON `json:"banner"`
}

type appearancePhotoJSON struct {
	File string `json:"file"`
	URL  string `json:"url,omitempty"`
	X    int    `json:"x"`
	Y    int    `json:"y"`
}

// AppearancePageData is the template data for /admin/appearance.
type AppearancePageData struct {
	PageData
	Enabled     bool
	Fabrics     []theme.Fabric
	State       appearanceState
	HasPrevious bool
	PreviewURL  string
}

func (s *Server) stateFromConfig(cfg *theme.Config) appearanceState {
	if cfg == nil {
		return appearanceState{Fabric: theme.DefaultFabric}
	}

	st := appearanceState{
		Fabric: cfg.Fabric, Main: cfg.Main, Highlight: cfg.Highlight, Second: cfg.Second,
	}
	st.Photo = s.photoJSON(cfg.Photo)
	st.Banner = s.photoJSON(cfg.Banner)

	return st
}

func (s *Server) photoJSON(p *theme.Photo) *appearancePhotoJSON {
	url := s.brandingURL(p)
	if url == "" {
		return nil
	}

	return &appearancePhotoJSON{File: filepath.Base(p.Path), URL: url, X: p.X, Y: p.Y}
}

// handleAdminAppearance renders the Appearance tab.
// GET /admin/appearance
func (s *Server) handleAdminAppearance(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()
	pd := s.newPageData(r)

	cfg, err := theme.ParseConfig(pd.Settings.Theme)
	if err != nil {
		s.logger.ErrorContext(ctx, "Unreadable stored theme; editor starts from the house look",
			slog.String("error", err.Error()))
		cfg = nil
	}

	preview := "/issues"
	if issue, err := s.store.GetLatestPublishedIssue(ctx, currentGroupID(ctx)); err == nil && issue != nil {
		preview = issuePublicPath(issue)
	}

	s.renderPage(w, "appearance.html", AppearancePageData{
		PageData:    pd,
		Enabled:     s.appearanceEnabled(ctx),
		Fabrics:     theme.Fabrics,
		State:       s.stateFromConfig(cfg),
		HasPrevious: pd.Settings.ThemePrevious != nil,
		PreviewURL:  preview,
	})
}

// requireAppearance rejects appearance API calls while the operator has the
// feature switched off.
func (s *Server) requireAppearance(w http.ResponseWriter, r *http.Request) bool {
	if s.appearanceEnabled(r.Context()) {
		return true
	}

	writeError(w, http.StatusForbidden, "appearance_paused",
		"Circle appearance is switched off for this instance")

	return false
}

// handleAppearancePreview resolves a draft palette for the live preview.
// POST /api/admin/appearance/preview
func (s *Server) handleAppearancePreview(w http.ResponseWriter, r *http.Request) {
	if !s.requireAppearance(w, r) {
		return
	}

	var req struct {
		Fabric    string `json:"fabric"`
		Main      string `json:"main"`
		Highlight string `json:"highlight"`
		Second    string `json:"second"`
	}
	if err := readJSON(r, &req); err != nil {
		writeError(w, http.StatusBadRequest, "invalid_request", "Invalid request body")
		return
	}

	cfg, err := theme.Config{
		Fabric: req.Fabric, Main: req.Main, Highlight: req.Highlight, Second: req.Second,
	}.Normalize()
	if err != nil {
		writeValidationError(w, map[string]string{"appearance": err.Error()})
		return
	}

	pal, err := theme.Resolve(cfg)
	if err != nil {
		writeValidationError(w, map[string]string{"appearance": err.Error()})
		return
	}

	writeJSON(w, http.StatusOK, map[string]any{
		"declarations": pal.Declarations(),
		"main":         pal.Main,
		"adjustments":  pal.Adjustments,
		"house":        cfg == nil,
	})
}

// handlePublishAppearance publishes the editor's state to the circle; the
// look it replaces becomes the restore point.
// PUT /api/admin/appearance
func (s *Server) handlePublishAppearance(w http.ResponseWriter, r *http.Request) {
	if !s.requireAppearance(w, r) {
		return
	}

	ctx := r.Context()
	groupID := currentGroupID(ctx)

	var req appearanceState
	if err := readJSON(r, &req); err != nil {
		writeError(w, http.StatusBadRequest, "invalid_request", "Invalid request body")
		return
	}

	cfg := theme.Config{Fabric: req.Fabric, Main: req.Main, Highlight: req.Highlight, Second: req.Second}
	for _, slot := range []struct {
		field string
		src   *appearancePhotoJSON
		dst   **theme.Photo
	}{{"photo", req.Photo, &cfg.Photo}, {"banner", req.Banner, &cfg.Banner}} {
		if slot.src == nil {
			continue
		}
		path, ok := s.brandingPath(groupID, slot.src.File)
		if !ok {
			writeValidationError(w, map[string]string{slot.field: "Upload the photo again — this one wasn't found"})
			return
		}
		*slot.dst = &theme.Photo{Path: path, X: slot.src.X, Y: slot.src.Y}
	}

	normalized, err := cfg.Normalize()
	if err != nil {
		writeValidationError(w, map[string]string{"appearance": err.Error()})
		return
	}

	settings, err := s.store.GetSettings(ctx, groupID)
	if err != nil {
		s.logger.ErrorContext(ctx, "Failed to load settings", slog.String("error", err.Error()))
		writeError(w, http.StatusInternalServerError, "server_error", "Internal server error")
		return
	}

	var raw json.RawMessage
	if normalized != nil {
		if raw, err = json.Marshal(normalized); err != nil {
			writeError(w, http.StatusInternalServerError, "server_error", "Internal server error")
			return
		}
	}

	previous := settings.ThemePrevious
	if string(raw) != string(settings.Theme) {
		// The replaced look becomes the restore point. The house look is
		// recorded as JSON null so "restore the house look" stays possible
		// and distinct from "no restore point" (NULL).
		previous = orNullJSON(settings.Theme)
	}

	s.saveTheme(w, r, groupID, raw, previous)
}

// handleRestoreAppearance swaps the published look with the one before it.
// POST /api/admin/appearance/restore
func (s *Server) handleRestoreAppearance(w http.ResponseWriter, r *http.Request) {
	if !s.requireAppearance(w, r) {
		return
	}

	ctx := r.Context()
	groupID := currentGroupID(ctx)

	settings, err := s.store.GetSettings(ctx, groupID)
	if err != nil {
		s.logger.ErrorContext(ctx, "Failed to load settings", slog.String("error", err.Error()))
		writeError(w, http.StatusInternalServerError, "server_error", "Internal server error")
		return
	}

	if settings.ThemePrevious == nil {
		writeError(w, http.StatusConflict, "nothing_to_restore", "There is no previous look to restore")
		return
	}

	restored := settings.ThemePrevious
	if string(restored) == "null" {
		restored = nil
	}

	s.saveTheme(w, r, groupID, restored, orNullJSON(settings.Theme))
}

func orNullJSON(raw json.RawMessage) json.RawMessage {
	if raw == nil {
		return json.RawMessage("null")
	}

	return raw
}

func (s *Server) saveTheme(w http.ResponseWriter, r *http.Request, groupID int64, current, previous json.RawMessage) {
	ctx := r.Context()

	if err := s.store.UpdateTheme(ctx, groupID, current, previous); err != nil {
		s.logger.ErrorContext(ctx, "Failed to save theme", slog.String("error", err.Error()))
		writeError(w, http.StatusInternalServerError, "server_error", "Failed to save appearance")
		return
	}

	s.pruneBranding(ctx, groupID, current, previous)

	cfg, _ := theme.ParseConfig(current)
	writeJSON(w, http.StatusOK, map[string]any{
		"state":        s.stateFromConfig(cfg),
		"has_previous": previous != nil,
	})
}

// ---- Circle photos --------------------------------------------------------

func (s *Server) brandingDir(groupID int64) string {
	return filepath.Join(s.config.UploadPath, brandingDirName, fmt.Sprint(groupID))
}

// brandingPath maps an editor file name to its on-disk path, accepting only
// generated names that exist in this circle's own branding directory.
func (s *Server) brandingPath(groupID int64, file string) (string, bool) {
	if !brandingFileRe.MatchString(file) {
		return "", false
	}

	p := filepath.Join(s.brandingDir(groupID), file)
	if info, err := os.Stat(p); err != nil || !info.Mode().IsRegular() {
		return "", false
	}

	return p, true
}

// pruneBranding deletes this circle's uploaded photos that neither the
// published look nor the restore point uses (abandoned drafts, replaced
// photos). Best-effort: a leftover file is harmless.
func (s *Server) pruneBranding(ctx context.Context, groupID int64, looks ...json.RawMessage) {
	keep := map[string]bool{}
	for _, raw := range looks {
		if cfg, err := theme.ParseConfig(raw); err == nil && cfg != nil {
			for _, p := range []*theme.Photo{cfg.Photo, cfg.Banner} {
				if p != nil {
					keep[filepath.Base(p.Path)] = true
				}
			}
		}
	}

	dir := s.brandingDir(groupID)
	entries, err := os.ReadDir(dir)
	if err != nil {
		return
	}
	for _, e := range entries {
		if e.IsDir() || keep[e.Name()] || !brandingFileRe.MatchString(e.Name()) {
			continue
		}
		if err := os.Remove(filepath.Join(dir, e.Name())); err != nil {
			s.logger.WarnContext(ctx, "Failed to prune circle photo",
				slog.String("file", e.Name()), slog.String("error", err.Error()))
		}
	}
}

// handleUploadAppearancePhoto stores a circle photo or banner as a
// metadata-free, downsized JPEG. The editor holds the returned file name in
// its draft; nothing is visible to members until the look is published.
// POST /api/admin/appearance/photo  (multipart: photo, slot=photo|banner)
func (s *Server) handleUploadAppearancePhoto(w http.ResponseWriter, r *http.Request) {
	if !s.requireAppearance(w, r) {
		return
	}

	ctx := r.Context()
	groupID := currentGroupID(ctx)

	r.Body = http.MaxBytesReader(w, r.Body, maxBrandingUploadBytes)
	if err := r.ParseMultipartForm(maxMultipartMemory); err != nil {
		writeError(w, http.StatusRequestEntityTooLarge, "too_large", "That photo is too large (30 MB max)")
		return
	}

	edge := circlePhotoEdge
	switch r.FormValue("slot") {
	case "photo":
	case "banner":
		edge = bannerEdge
	default:
		writeValidationError(w, map[string]string{"slot": "Must be photo or banner"})
		return
	}

	file, _, err := r.FormFile("photo")
	if err != nil {
		writeError(w, http.StatusBadRequest, "invalid_request", "Missing photo in form")
		return
	}
	defer file.Close()

	dir := s.brandingDir(groupID)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		s.logger.ErrorContext(ctx, "Failed to create branding directory", slog.String("error", err.Error()))
		writeError(w, http.StatusInternalServerError, "server_error", "Failed to save photo")
		return
	}

	name := auth.GenerateRandomString(8) + ".jpg"
	dst := filepath.Join(dir, name)

	if err := s.storeBrandingImage(ctx, file, edge, dst); err != nil {
		msg := "Couldn't read that photo — try a JPEG, PNG, WebP or HEIC"
		var bad badImageError
		if errors.As(err, &bad) {
			msg = bad.msg
		} else {
			s.logger.ErrorContext(ctx, "Failed to process circle photo", slog.String("error", err.Error()))
		}
		writeError(w, http.StatusUnprocessableEntity, "unsupported_image", msg)
		return
	}

	writeJSON(w, http.StatusCreated, appearancePhotoJSON{
		File: name, URL: s.uploadURL(dst), X: 50, Y: 50,
	})
}
