package server

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"html/template"
	"log/slog"
	"net/http"
	"os"
	"path/filepath"
	"regexp"
	"strconv"
	"time"

	"github.com/parithosh/piecesoflife/internal/auth"
	"github.com/parithosh/piecesoflife/internal/store"
	"github.com/parithosh/piecesoflife/internal/theme"
)

// Circle appearance: a circle admin picks a fabric, up to three colours and
// optional photos; the operator's instance switch is a ceiling over all of
// it. Enforcement happens where themes are rendered (newPageData and the
// memento page) and on every appearance API — never only in the UI.

// pageTheme is the appearance a page renders with; nil = the house look,
// which emits nothing so pages stay byte-identical to the un-themed app.
type pageTheme struct {
	// CSS is the :root declaration list: palette tokens plus, when photos
	// are shown, --circle-photo/--banner and their focal points.
	CSS       template.CSS
	Main      string
	HasPhoto  bool
	HasBanner bool
}

// LoopEntry is one circle in the nav switcher and on /loops: the
// membership plus its appearance summary (empty when the circle uses the
// house look or appearance is switched off).
type LoopEntry struct {
	store.UserGroup
	Dot      string
	PhotoURL string
	PhotoPos string
}

// brandingFileRe is the only shape a stored circle photo file can take —
// generated by the upload handler, so anything else is a forged reference.
var brandingFileRe = regexp.MustCompile(`^[0-9a-f]{16}\.jpg$`)

const (
	brandingDirName = "branding"
	// maxBrandingUploadBytes bounds a circle photo upload: phone photos are
	// a few MB; 30 MB leaves room for large PNGs.
	maxBrandingUploadBytes = 30 << 20
	// brandingFormMemory keeps multipart parsing from holding the photo in
	// memory: anything larger spills to a temp file on disk.
	brandingFormMemory = 1 << 20
	circlePhotoEdge    = 640
	bannerEdge         = 2400
	// brandingDraftGrace is how long an uploaded-but-unpublished photo is
	// safe from cleanup: an admin may still be editing in another tab.
	// Drafts the editor discards are deleted immediately instead.
	brandingDraftGrace = 24 * time.Hour
)

// appearanceEnabled reports the operator's instance switch.
func (s *Server) appearanceEnabled(ctx context.Context) bool {
	inst, err := s.store.GetInstanceSettings(ctx)
	if err != nil {
		s.logger.ErrorContext(ctx, "Failed to load instance settings",
			slog.String("error", err.Error()))
		return false
	}

	return inst.AllowCircleAppearance
}

// resolveTheme turns a group's stored config into render data. withPhotos
// is false for surfaces anonymous visitors can reach (public mementos):
// colours only, so no private photo URL ever appears in the page. The
// caller has already checked the instance switch.
func (s *Server) resolveTheme(ctx context.Context, groupID int64, raw json.RawMessage, withPhotos bool) *pageTheme {
	cfg, err := theme.ParseConfig(raw)
	if err != nil {
		s.logger.ErrorContext(ctx, "Ignoring unreadable circle theme",
			slog.Int64("group_id", groupID), slog.String("error", err.Error()))
		return nil
	}
	if cfg == nil {
		return nil
	}

	pal, err := theme.Resolve(cfg)
	if err != nil {
		s.logger.ErrorContext(ctx, "Ignoring invalid circle theme",
			slog.Int64("group_id", groupID), slog.String("error", err.Error()))
		return nil
	}

	pt := &pageTheme{Main: pal.Main}
	decls := pal.Declarations()

	if withPhotos {
		if url := s.brandingURL(groupID, cfg.Photo); url != "" {
			pt.HasPhoto = true
			decls += photoDecls("circle-photo", url, cfg.Photo)
		}
		if url := s.brandingURL(groupID, cfg.Banner); url != "" {
			pt.HasBanner = true
			decls += photoDecls("banner", url, cfg.Banner)
		}
	}

	// Safe: every palette value is engine-generated hex/rgb, and photo URLs
	// are rebuilt by brandingURL from a numeric group id and a file name
	// matching brandingFileRe — nothing from the stored path is echoed.
	pt.CSS = template.CSS(decls) //nolint:gosec // see above

	return pt
}

func photoDecls(name, url string, p *theme.Photo) string {
	return fmt.Sprintf(`--%s:url("%s");--%s-pos:%d%% %d%%;`, name, url, name, p.X, p.Y)
}

// brandingURL returns the /uploads URL of a group's stored circle photo, or
// "" unless the stored path is exactly a generated file inside that
// group's own branding directory. The URL is built from the validated
// parts, never from the stored string, so a tampered path cannot inject
// markup into the page's <style>.
func (s *Server) brandingURL(groupID int64, p *theme.Photo) string {
	if p == nil {
		return ""
	}

	file := filepath.Base(p.Path)
	if !brandingFileRe.MatchString(file) ||
		filepath.Clean(p.Path) != filepath.Join(s.brandingDir(groupID), file) {
		return ""
	}

	return fmt.Sprintf("/uploads/%s/%d/%s", brandingDirName, groupID, file)
}

// loopEntries decorates the user's circles with their appearance summary.
func (s *Server) loopEntries(groups []store.UserGroup, enabled bool) []LoopEntry {
	out := make([]LoopEntry, len(groups))
	for i, g := range groups {
		out[i] = LoopEntry{UserGroup: g}
		if !enabled || g.Theme == nil {
			continue
		}

		cfg, err := theme.ParseConfig(g.Theme)
		if err != nil || cfg == nil {
			continue
		}
		if pal, err := theme.Resolve(cfg); err == nil {
			out[i].Dot = pal.Main
		}
		if url := s.brandingURL(g.GroupID, cfg.Photo); url != "" {
			out[i].PhotoURL = url
			out[i].PhotoPos = fmt.Sprintf("%d%% %d%%", cfg.Photo.X, cfg.Photo.Y)
		}
	}

	return out
}

// ---- Appearance page ------------------------------------------------------

// appearanceState is the editor's JSON view of a config: photos travel as
// bare file names plus URLs, never as server paths. GroupID names the
// circle the editor was opened for (see requireEditorCircle); Revision
// identifies the stored look the editor started from, so publishing over
// a look someone else saved in the meantime is refused, not silent.
type appearanceState struct {
	GroupID   int64                `json:"group_id,omitempty"`
	Revision  string               `json:"revision"`
	Fabric    string               `json:"fabric"`
	Main      string               `json:"main"`
	Highlight string               `json:"highlight"`
	Second    string               `json:"second"`
	Photo     *appearancePhotoJSON `json:"photo"`
	Banner    *appearancePhotoJSON `json:"banner"`
}

// themeRevision is an opaque fingerprint of a stored look (NULL included).
func themeRevision(raw json.RawMessage) string {
	sum := sha256.Sum256(raw)
	return hex.EncodeToString(sum[:8])
}

type appearancePhotoJSON struct {
	File string `json:"file"`
	URL  string `json:"url,omitempty"`
	X    int    `json:"x"`
	Y    int    `json:"y"`
}

// AppearancePageData is the template data for /admin/appearance.
type AppearancePageData struct {
	PageData
	Enabled     bool
	Fabrics     []theme.Fabric
	State       appearanceState
	HasPrevious bool
	PreviewURL  string
}

// stateFor builds the editor state for a group's stored look. An
// unreadable look opens as the house look but keeps its revision.
func (s *Server) stateFor(ctx context.Context, groupID int64, raw json.RawMessage) appearanceState {
	st := appearanceState{Revision: themeRevision(raw), Fabric: theme.DefaultFabric}

	cfg, err := theme.ParseConfig(raw)
	if err != nil {
		s.logger.ErrorContext(ctx, "Unreadable stored theme; editor starts from the house look",
			slog.Int64("group_id", groupID), slog.String("error", err.Error()))
	}
	if cfg == nil {
		return st
	}

	st.Fabric, st.Main, st.Highlight, st.Second = cfg.Fabric, cfg.Main, cfg.Highlight, cfg.Second
	st.Photo = s.photoJSON(groupID, cfg.Photo)
	st.Banner = s.photoJSON(groupID, cfg.Banner)

	return st
}

func (s *Server) photoJSON(groupID int64, p *theme.Photo) *appearancePhotoJSON {
	url := s.brandingURL(groupID, p)
	if url == "" {
		return nil
	}

	return &appearancePhotoJSON{File: filepath.Base(p.Path), URL: url, X: p.X, Y: p.Y}
}

// handleAdminAppearance renders the Appearance tab.
// GET /admin/appearance
func (s *Server) handleAdminAppearance(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()
	pd := s.newPageData(r)
	groupID := currentGroupID(ctx)

	preview := "/issues"
	if issue, err := s.store.GetLatestPublishedIssue(ctx, groupID); err == nil && issue != nil {
		preview = issuePublicPath(issue)
	}

	s.renderPage(w, "appearance.html", AppearancePageData{
		PageData:    pd,
		Enabled:     s.appearanceEnabled(ctx),
		Fabrics:     theme.Fabrics,
		State:       s.stateFor(ctx, groupID, pd.Settings.Theme),
		HasPrevious: pd.Settings.ThemePrevious != nil,
		PreviewURL:  preview,
	})
}

// requireAppearance rejects appearance API calls while the operator has the
// feature switched off.
func (s *Server) requireAppearance(w http.ResponseWriter, r *http.Request) bool {
	if s.appearanceEnabled(r.Context()) {
		return true
	}

	writeError(w, http.StatusForbidden, "appearance_paused",
		"Circle appearance is switched off for this instance")

	return false
}

// requireEditorCircle rejects a request whose editor was opened for a
// different circle than the session's current one. The current circle is
// session state shared by every tab, so switching circles elsewhere must
// not redirect this editor's uploads and publishes to the wrong circle.
func requireEditorCircle(w http.ResponseWriter, r *http.Request, editorGroupID int64) bool {
	if editorGroupID != 0 && editorGroupID == currentGroupID(r.Context()) {
		return true
	}

	writeError(w, http.StatusConflict, "wrong_circle",
		"You switched circles in another tab — reload this page before changing its appearance")

	return false
}

// handleAppearancePreview resolves a draft palette for the live preview.
// POST /api/admin/appearance/preview
func (s *Server) handleAppearancePreview(w http.ResponseWriter, r *http.Request) {
	if !s.requireAppearance(w, r) {
		return
	}

	var req struct {
		GroupID   int64  `json:"group_id"`
		Fabric    string `json:"fabric"`
		Main      string `json:"main"`
		Highlight string `json:"highlight"`
		Second    string `json:"second"`
	}
	if err := readJSON(r, &req); err != nil {
		writeError(w, http.StatusBadRequest, "invalid_request", "Invalid request body")
		return
	}
	if !requireEditorCircle(w, r, req.GroupID) {
		return
	}

	cfg, err := theme.Config{
		Fabric: req.Fabric, Main: req.Main, Highlight: req.Highlight, Second: req.Second,
	}.Normalize()
	if err != nil {
		writeValidationError(w, map[string]string{"appearance": err.Error()})
		return
	}

	pal, err := theme.Resolve(cfg)
	if err != nil {
		writeValidationError(w, map[string]string{"appearance": err.Error()})
		return
	}

	writeJSON(w, http.StatusOK, map[string]any{
		"declarations": pal.Declarations(),
		"main":         pal.Main,
		"adjustments":  pal.Adjustments,
		"house":        cfg == nil,
	})
}

// handlePublishAppearance publishes the editor's state to the circle; the
// look it replaces becomes the restore point.
// PUT /api/admin/appearance
func (s *Server) handlePublishAppearance(w http.ResponseWriter, r *http.Request) {
	if !s.requireAppearance(w, r) {
		return
	}

	ctx := r.Context()

	var req appearanceState
	if err := readJSON(r, &req); err != nil {
		writeError(w, http.StatusBadRequest, "invalid_request", "Invalid request body")
		return
	}
	if !requireEditorCircle(w, r, req.GroupID) {
		return
	}
	groupID := req.GroupID

	s.brandingMu.Lock()
	defer s.brandingMu.Unlock()

	cfg := theme.Config{Fabric: req.Fabric, Main: req.Main, Highlight: req.Highlight, Second: req.Second}
	for _, slot := range []struct {
		field string
		src   *appearancePhotoJSON
		dst   **theme.Photo
	}{{"photo", req.Photo, &cfg.Photo}, {"banner", req.Banner, &cfg.Banner}} {
		if slot.src == nil {
			continue
		}
		path, ok := s.brandingPath(groupID, slot.src.File)
		if !ok {
			writeValidationError(w, map[string]string{slot.field: "Upload the photo again — this one wasn't found"})
			return
		}
		*slot.dst = &theme.Photo{Path: path, X: slot.src.X, Y: slot.src.Y}
	}

	normalized, err := cfg.Normalize()
	if err != nil {
		writeValidationError(w, map[string]string{"appearance": err.Error()})
		return
	}

	var raw json.RawMessage
	if normalized != nil {
		if raw, err = json.Marshal(normalized); err != nil {
			writeError(w, http.StatusInternalServerError, "server_error", "Internal server error")
			return
		}
	}

	settings, err := s.store.GetSettings(ctx, groupID)
	if err != nil {
		s.logger.ErrorContext(ctx, "Failed to load settings", slog.String("error", err.Error()))
		writeError(w, http.StatusInternalServerError, "server_error", "Internal server error")
		return
	}

	// The editor must have started from the look that is stored now;
	// otherwise another admin published in between and we would silently
	// overwrite their work. (PublishTheme's own compare-and-swap then
	// covers the window between this read and the write.)
	if req.Revision != themeRevision(settings.Theme) {
		s.finishThemeChange(w, r, groupID, store.ErrThemeChanged)
		return
	}

	err = s.store.PublishTheme(ctx, groupID, settings.Theme, raw)
	s.finishThemeChange(w, r, groupID, err)
}

// handleRestoreAppearance swaps the published look with the one before it.
// POST /api/admin/appearance/restore
func (s *Server) handleRestoreAppearance(w http.ResponseWriter, r *http.Request) {
	if !s.requireAppearance(w, r) {
		return
	}

	var req struct {
		GroupID int64 `json:"group_id"`
	}
	if err := readJSON(r, &req); err != nil {
		writeError(w, http.StatusBadRequest, "invalid_request", "Invalid request body")
		return
	}
	if !requireEditorCircle(w, r, req.GroupID) {
		return
	}

	s.brandingMu.Lock()
	defer s.brandingMu.Unlock()

	err := s.store.RestoreTheme(r.Context(), req.GroupID)
	s.finishThemeChange(w, r, req.GroupID, err)
}

// finishThemeChange answers a publish/restore from the authoritative,
// just-committed state and cleans up photos neither look uses. Callers
// hold brandingMu.
func (s *Server) finishThemeChange(w http.ResponseWriter, r *http.Request, groupID int64, err error) {
	ctx := r.Context()

	switch {
	case errors.Is(err, store.ErrThemeChanged):
		writeError(w, http.StatusConflict, "appearance_changed",
			"Someone else changed this circle's look — reload to see it")
		return
	case errors.Is(err, store.ErrNoRestorePoint):
		writeError(w, http.StatusConflict, "nothing_to_restore", "There is no previous look to restore")
		return
	case err != nil:
		s.logger.ErrorContext(ctx, "Failed to save theme", slog.String("error", err.Error()))
		writeError(w, http.StatusInternalServerError, "server_error", "Failed to save appearance")
		return
	}

	settings, err := s.store.GetSettings(ctx, groupID)
	if err != nil {
		s.logger.ErrorContext(ctx, "Failed to reload settings", slog.String("error", err.Error()))
		writeError(w, http.StatusInternalServerError, "server_error", "Internal server error")
		return
	}

	s.pruneBranding(ctx, groupID, settings, brandingDraftGrace)

	writeJSON(w, http.StatusOK, map[string]any{
		"state":        s.stateFor(ctx, groupID, settings.Theme),
		"has_previous": settings.ThemePrevious != nil,
	})
}

// ---- Circle photos --------------------------------------------------------

func (s *Server) brandingDir(groupID int64) string {
	return filepath.Join(s.config.UploadPath, brandingDirName, strconv.FormatInt(groupID, 10))
}

// brandingPath maps an editor file name to its on-disk path, accepting only
// generated names that exist in this circle's own branding directory.
func (s *Server) brandingPath(groupID int64, file string) (string, bool) {
	if !brandingFileRe.MatchString(file) {
		return "", false
	}

	p := filepath.Join(s.brandingDir(groupID), file)
	if info, err := os.Stat(p); err != nil || !info.Mode().IsRegular() {
		return "", false
	}

	return p, true
}

// brandingInUse lists the photo files a group's published look and restore
// point reference.
func brandingInUse(settings *store.Settings) map[string]bool {
	keep := map[string]bool{}
	for _, raw := range []json.RawMessage{settings.Theme, settings.ThemePrevious} {
		cfg, err := theme.ParseConfig(raw)
		if err != nil || cfg == nil {
			continue
		}
		for _, p := range []*theme.Photo{cfg.Photo, cfg.Banner} {
			if p != nil {
				keep[filepath.Base(p.Path)] = true
			}
		}
	}

	return keep
}

// pruneBranding deletes this circle's photos that neither the published
// look nor the restore point uses and that are older than grace, judged
// against the stored (authoritative) settings. Callers hold brandingMu.
// Best-effort: a leftover file is harmless.
func (s *Server) pruneBranding(ctx context.Context, groupID int64, settings *store.Settings, grace time.Duration) {
	keep := brandingInUse(settings)
	dir := s.brandingDir(groupID)

	entries, err := os.ReadDir(dir)
	if err != nil {
		return
	}

	cutoff := time.Now().Add(-grace)
	for _, e := range entries {
		if e.IsDir() || keep[e.Name()] || !brandingFileRe.MatchString(e.Name()) {
			continue
		}
		if info, err := e.Info(); err != nil || info.ModTime().After(cutoff) {
			continue
		}
		if err := os.Remove(filepath.Join(dir, e.Name())); err != nil {
			s.logger.WarnContext(ctx, "Failed to prune circle photo",
				slog.String("file", e.Name()), slog.String("error", err.Error()))
		}
	}
}

// handleDeleteAppearancePhoto deletes a draft photo the editor no longer
// uses. Files the published look or restore point reference are kept, so
// the call is always safe to make; the answer is 204 either way.
// DELETE /api/admin/appearance/photo/{file}?group_id=N
func (s *Server) handleDeleteAppearancePhoto(w http.ResponseWriter, r *http.Request) {
	if !s.requireAppearance(w, r) {
		return
	}

	editorGroupID, _ := strconv.ParseInt(r.URL.Query().Get("group_id"), 10, 64)
	if !requireEditorCircle(w, r, editorGroupID) {
		return
	}

	file := r.PathValue("file")
	if !brandingFileRe.MatchString(file) {
		writeError(w, http.StatusNotFound, "not_found", "No such photo")
		return
	}

	ctx := r.Context()

	s.brandingMu.Lock()
	defer s.brandingMu.Unlock()

	settings, err := s.store.GetSettings(ctx, editorGroupID)
	if err != nil {
		s.logger.ErrorContext(ctx, "Failed to load settings", slog.String("error", err.Error()))
		writeError(w, http.StatusInternalServerError, "server_error", "Internal server error")
		return
	}

	if !brandingInUse(settings)[file] {
		err := os.Remove(filepath.Join(s.brandingDir(editorGroupID), file))
		if err != nil && !errors.Is(err, os.ErrNotExist) {
			s.logger.WarnContext(ctx, "Failed to delete draft circle photo",
				slog.String("file", file), slog.String("error", err.Error()))
		}
	}

	w.WriteHeader(http.StatusNoContent)
}

// handleUploadAppearancePhoto stores a circle photo or banner as a
// metadata-free, downsized JPEG. The editor holds the returned file name in
// its draft; nothing is visible to members until the look is published.
// POST /api/admin/appearance/photo  (multipart: photo, slot=photo|banner, group_id)
func (s *Server) handleUploadAppearancePhoto(w http.ResponseWriter, r *http.Request) {
	if !s.requireAppearance(w, r) {
		return
	}

	ctx := r.Context()

	r.Body = http.MaxBytesReader(w, r.Body, maxBrandingUploadBytes)
	if err := r.ParseMultipartForm(brandingFormMemory); err != nil {
		writeError(w, http.StatusRequestEntityTooLarge, "too_large", "That photo is too large (30 MB max)")
		return
	}

	editorGroupID, _ := strconv.ParseInt(r.FormValue("group_id"), 10, 64)
	if !requireEditorCircle(w, r, editorGroupID) {
		return
	}

	edge := circlePhotoEdge
	switch r.FormValue("slot") {
	case "photo":
	case "banner":
		edge = bannerEdge
	default:
		writeValidationError(w, map[string]string{"slot": "Must be photo or banner"})
		return
	}

	file, _, err := r.FormFile("photo")
	if err != nil {
		writeError(w, http.StatusBadRequest, "invalid_request", "Missing photo in form")
		return
	}
	defer file.Close()

	dir := s.brandingDir(editorGroupID)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		s.logger.ErrorContext(ctx, "Failed to create branding directory", slog.String("error", err.Error()))
		writeError(w, http.StatusInternalServerError, "server_error", "Failed to save photo")
		return
	}

	name := auth.GenerateRandomString(8) + ".jpg"
	dst := filepath.Join(dir, name)

	if err := s.storeBrandingImage(ctx, file, edge, dst); err != nil {
		var bad badImageError
		if errors.As(err, &bad) {
			writeError(w, http.StatusUnprocessableEntity, "unsupported_image", bad.msg)
			return
		}
		s.logger.ErrorContext(ctx, "Failed to store circle photo", slog.String("error", err.Error()))
		writeError(w, http.StatusInternalServerError, "server_error", "Couldn't save the photo — please try again")
		return
	}

	writeJSON(w, http.StatusCreated, appearancePhotoJSON{
		File: name, URL: fmt.Sprintf("/uploads/%s/%d/%s", brandingDirName, editorGroupID, name), X: 50, Y: 50,
	})
}
